steps:
    # Fetch up-to-date submodules
    - name: 'gcr.io/cloud-builders/git'
      secretEnv: [ 'SSH_KEY' ]
      entrypoint: 'bash'
      args:
          - -c
          - |
              echo "$$SSH_KEY" >> /root/.ssh/id_rsa
              chmod 400 /root/.ssh/id_rsa
              cp known_hosts.github /root/.ssh/known_hosts
      volumes:
          - name: 'ssh'
            path: /root/.ssh

    - name: gcr.io/cloud-builders/git
      args: [ 'submodule', 'update', '--init', '--recursive' ]
      volumes:
          - name: 'ssh'
            path: /root/.ssh

    - name: 'bash'
      args: ["-c", "chmod +x ./gradlefilereplacer.sh"]

    - name: 'bash'
      args: ['./gradlefilereplacer.sh']

        # Replace the gradle.properties file with the content of the axelor-gradle-properties-staging secret
    - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args: [ "-c", "mkdir -p /workspace/open-suite-webapp && echo -e $$GRADLE_PROPERTIES > /workspace/open-suite-webapp/gradle.properties" ]
      secretEnv: [ "GRADLE_PROPERTIES" ]

    # Build with Java's Gradle
    - name: 'gradle:8.4.0-jdk11'
      dir: './open-suite-webapp'
      entrypoint: "bash"
      args: [ "-c", "./gradlew --no-daemon build"]

    # Create the Docker image
    - name: 'gcr.io/cloud-builders/docker'
      args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:latest", "-f", "dockerfile", "."]

    # Save the image in Artifact Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME", "--all-tags"]

    # Deploy image on service
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args: ['run','deploy','${_SERVICE_NAME}','--image','gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA','--region','europe-west9','--allow-unauthenticated']

images:
    - 'gcr.io/$PROJECT_ID/$REPO_NAME'

timeout: 40m

availableSecrets:
    secretManager:
        - versionName: projects/$PROJECT_ID/secrets/secret-github-ssh/versions/latest
          env: 'SSH_KEY'
        - versionName: projects/$PROJECT_ID/secrets/axelor-gradle-properties/versions/latest
          env: 'GRADLE_PROPERTIES'

options:
    logging: CLOUD_LOGGING_ONLY
